Exercise 3
chloemarie95/DevOps-Course-Starter pull request #6
Opened 2021-06-02 11:16 UTC by chloemarie95

2021-06-09 13:00 UTC, hugh-emerson requested changes
Almost there. See my comments for some suggestions, but the main issue is that your e2e test doesn't run because `create_board` doesn't exist.

Also, your README needs updating:
- How to run the tests
- Prerequisites (Firefox & geckodriver)

2021-06-09 13:00 UTC, hugh-emerson commented on geckodriver.log
> +1620730075325	geckodriver	INFO	Listening on 127.0.0.1:50117
This file should be deleted from the repository and `geckodriver.log` added to the .gitignore.

2021-06-09 13:00 UTC, hugh-emerson commented on e2e_test/e2e_test.py
> +    time.sleep(4)
Sleep means you are forcing this test to take longer than it needs to. Selenium will already wait for the page to load by default when you call the driver.get function

2021-06-09 13:00 UTC, hugh-emerson commented on e2e_test/e2e_test.py
> +    time.sleep(2)
You can use the driver's `implicitly_wait` which means that whenever you try to find elements with the driver, it will wait **up to** that many seconds for the element to appear.

2021-06-09 13:00 UTC, hugh-emerson commented on e2e_test/e2e_test.py
> +    doingItemPath = '/html/body/div/div[2]/div[2]/div/ul[2]/div[1]/li/ul/div/div[2]'
This full path means your test will break if any of the page structure changes.

It would be much better to find by a `class` on the element. You should **at least** find the `ul` by id, skipping the first few divs.

2021-06-09 13:00 UTC, hugh-emerson commented on e2e_test/e2e_test.py
> +def test_change_doing_item(driver, test_app):
This test does not do what it says. It just checks that a certain element on the page has the expected text, it doesn't make a "Doing" item. But you can just delete this test for now.

2021-06-09 13:00 UTC, hugh-emerson commented on e2e_test/selenium_test.py
> +    assert driver.title == 'To-Do App'
Did you mean to delete this file? Seems superseded by the e2e_test.py file

2021-06-09 13:00 UTC, hugh-emerson commented on e2e_test/e2e_test.py
> +    board_id = service.create_board("E2E Test board")
There is no `create_board` function? Did you forget to push some other changes?

Note that you will also need to set e.g. `os.environ['TRELLO_TODO_ID']` for this test to work.

2021-06-09 13:00 UTC, hugh-emerson commented on tests/test_integration.py
> +    assert str(response.data).find("New Todo")
`assert` fails a test if the expression that follows is false (or "falsy")

`.find` returns the index of the substring you are looking for. It returns -1 if it can't find it. `-1` is Truthy.

That means this test **passes** if it can't find "New Todo". The only time the test will fail is if .find returns 0, which happens if the string starts with "New Todo". What you want is `assert str(response.data).find("New Todo") > -1` or a clearer alternative: `assert "New Todo" in str(response.data)`

And in fact, that is what is happening. Your stub data (from `sample_trello_cards_response`) only has a card titled "Test Todo name". Replace "New Todo" with the correct value.

2021-07-13 14:49 UTC, closed without merging

2021-07-13 14:49 UTC, chloemarie95 commented
raising new PR for amendments made